In [1]:
import numpy as np

# numpy的基本使用

In [3]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])

In [7]:
#获取维度
print(a.ndim)
print(b.ndim)

1
2


In [8]:
#获取形状
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [11]:
#获取类型
print(a.dtype)
print(b.dtype)
#默认是int32,但因为我们设置的2个数组的数字大小比较小，我们可以指定为int16
a = np.array([1,2,3],dtype='int16')
print(a.dtype)
print(b.dtype)

int32
int32
int16
int32


In [13]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])

In [14]:
#获取数据的大小，int32是4bytes,int16是2bytes
print(a.itemsize)
a = np.array([1,2,3],dtype='int16')
print(a.itemsize)

4
2


In [15]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])

In [16]:
print(a.size)
print(b.size)

3
6


In [17]:
#获取字节大小
print(a.nbytes)
print(b.nbytes)

12
24


In [20]:
#获取特定位置的元素
print(b[1,2])
print(b[-1,-1])

6
6


In [24]:
#获取特定的行
print(b[0,:])
print(b[0])
#获取特定的列
print(b[:,0])

[1 2 3]
[1 2 3]
[1 4]


In [26]:
#以特定的步长获取多个元素2,4,6,8
a=np.array([[1,2,3,4,5,6,7,8,9],[11,22,33,44,55,66,77,88,99]])
print(a[0,1:8:2])

[2 4 6 8]


In [28]:
#改变特定位置的元素
a=np.array([[1,2,3,4,5,6,7,8,9],[11,22,33,44,55,66,77,88,99]])
a[0,0]=0
print(a)

[[ 0  2  3  4  5  6  7  8  9]
 [11 22 33 44 55 66 77 88 99]]


In [31]:
#三维数组中获取特定位置的元素6
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b[1,0,1])

6


In [35]:
#初始化全1矩阵
a=np.ones(3)
b=np.ones((2,3))
c=np.ones((2,2,2))
print(a)
print(b)
print(c)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [39]:
#初始化全x矩阵
x=9
a=np.full((2,2),x)
print(a)

[[9 9]
 [9 9]]


In [40]:
#生成随机数
np.random.rand(4,2)

array([[0.32719944, 0.60202487],
       [0.1377539 , 0.7480258 ],
       [0.55890584, 0.94970265],
       [0.93089125, 0.07948315]])

In [44]:
np.random.randint(2,size=(4,2))

array([[0, 0],
       [1, 0],
       [1, 1],
       [1, 0]])

In [47]:
np.random.randint(-9,5,size=(4,2))

array([[-8,  4],
       [ 3,  4],
       [-5, -1],
       [-5,  1]])

In [49]:
#生成单位矩阵
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [53]:
#复制数组
arr=np.array([[1,2,3]])
arr2 = np.repeat(arr,4,axis=0)
print(arr2)
arr3 = np.repeat(arr,4,axis=1)
print(arr3)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 1 2 2 2 2 3 3 3 3]]


In [56]:
#numpy的拷贝
#浅拷贝，只是拷贝了值，地址还是共用的
a=np.array([1,2,3])
b=a
print(a)
print(b)
b[0]=99
print(a)
print(b)

[1 2 3]
[1 2 3]
[99  2  3]
[99  2  3]


In [57]:
#深拷贝，拷贝了值，还自己创建了一个地址空间
a=np.array([1,2,3])
b=a.copy()
print(a)
print(b)
b[0]=99
print(a)
print(b)

[1 2 3]
[1 2 3]
[1 2 3]
[99  2  3]


# 1.numpy的数学运算

In [58]:
a= np.array([1,2,3])

In [65]:
a*2

array([2, 4, 6])

In [60]:
a-2

array([-1,  0,  1])

In [61]:
a+2

array([3, 4, 5])

In [62]:
a/2

array([0.5, 1. , 1.5])

In [64]:
a%2

array([1, 0, 1], dtype=int32)

In [66]:
a**2

array([1, 4, 9], dtype=int32)

In [67]:
a= np.array([1,2,3])
b=np.array([4,5,6])

In [68]:
a+b

array([5, 7, 9])

In [69]:
a*b

array([ 4, 10, 18])

In [71]:
#取sin值
a=np.array([1, 2,3])
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [72]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

# 统计

In [73]:
stats = np.array([[1,2,3],[4,5,6]])

In [79]:
np.min(stats)

array([1, 4])

In [75]:
np.max(stats)

6

In [80]:
np.sum(stats)

21

# 重组数组

In [85]:
before = np.array([[1,2,3],[4,5,6]])
print(before)
after= before.reshape((2,3,1))
print(after)

[[1 2 3]
 [4 5 6]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


# 堆叠数组

In [90]:
arr = np.array([1,2,3])
arr2 = np.array([4,5,6])


In [91]:
arr3 = np.vstack((arr,arr2))
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
arr4=np.hstack((arr,arr2))
arr4

array([1, 2, 3, 4, 5, 6])

In [94]:
filedata=np.genfromtxt('NumPy-master/data.txt',delimiter=',')
filedata=filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [96]:
filedata >50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [97]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [98]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,3]]

array([2, 3, 4])

In [101]:
filedata=np.genfromtxt('NumPy-master/data.txt',delimiter=',')
filedata=filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [100]:
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [102]:
np.all(filedata>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [103]:
np.any(filedata>50,axis=1)

array([ True,  True,  True])

In [104]:
np.all(filedata>50,axis=1)

array([False, False, False])

In [105]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [107]:
~((filedata>50)&(filedata<100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])