In [1]:
import tensorflow as tf

vector是一个一维的，matrics是二维的

# 创建一个张量

In [2]:
tf.constant(4)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [3]:
tf.constant(4.0)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [4]:
tf.constant(4,shape=(1,1))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[4]])>

In [5]:
tf.constant(4,shape=(1,1),dtype=tf.float32)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [6]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [7]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [8]:
tf.zeros((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

对角线为1的单位矩阵identity matrix

In [10]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

mean是正态分布的平均值，stddev是正态分布的标准差

In [11]:
tf.random.normal((3,3),mean=0,stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.774337  , -0.20476985, -1.7366977 ],
       [ 0.40055254, -1.6781529 ,  0.79777634],
       [-0.04213721,  0.96475106, -1.3462292 ]], dtype=float32)>

In [12]:
tf.random.uniform((3,3),minval=0,maxval=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.5326619 , 0.38693714, 0.22828817],
       [0.18783474, 0.26956105, 0.665699  ],
       [0.90568316, 0.6489365 , 0.4047451 ]], dtype=float32)>

In [13]:
 tf.range(9)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

delta是python里面的步长path

In [14]:
tf.range(start=1,limit=10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

cast相当于一种强制类型转换<br>
相当于float(1,3,5,7,9)

In [15]:
tf.cast(tf.range(start=1,limit=10,delta=2),dtype=tf.float32)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 3., 5., 7., 9.], dtype=float32)>

# 张量的数学操作

加法

In [19]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
tf.add(x,y),x+y

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>)

减法

In [20]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
tf.subtract(x,y),x-y

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4])>)

In [21]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
tf.divide(x,y),x/y

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>,
 <tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>)

In [22]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
tf.multiply(x,y),x*y

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21])>)

In [24]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
tf.tensordot(x,y,axes=1),tf.reduce_sum(x*y,axis=0)

(<tf.Tensor: shape=(), dtype=int32, numpy=46>,
 <tf.Tensor: shape=(), dtype=int32, numpy=46>)

每个元素的n次方

In [26]:
x=tf.constant([1,2,3])
x**5

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243])>

In [29]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [30]:
tf.constant([[7,8],[9,10],[11,12]])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])>

矩阵相乘

In [31]:
x=tf.constant([[1,2,3],[4,5,6]])
y=tf.constant([[7,8],[9,10],[11,12]])
tf.matmul(x,y),x@y

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]])>)

In [32]:
x=tf.constant([0,1,2,3,4,5,6,7,8,9])
x,x[:],x[::2],x[::-1]

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])>)

现在我们要根据下标取特定的值

In [33]:
x=tf.constant([0,1,2,3,4,5,6,7,8,9])
index = tf.constant([0,3])
x_index = tf.gather(x,index)
x_index

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 3])>

In [35]:
x= tf.constant([[1,2],
                [3,4],
                [5,6]])
x,x[0],x[0,:],x[0:2,:],x[2,1],x[1:3,1]

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6])>)

矩阵重塑

In [36]:
x=tf.range(9)
y=tf.reshape(x,(3,3))
x,y

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])>)

矩阵的转换

In [37]:
x=tf.constant([[1,2,3],
              [4,5,6],
              [7,8,9]])
y=tf.transpose(x,perm=[1,0])
x,y

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])>)